---
title: "assignment 5"
author: "Kyle Monper"
date: "November 26, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r, include=FALSE}
#load packages
library(tidyverse)
library(effsize)
library(gridExtra)
```

```{r, include=FALSE}
#load files

faculty_salary <- read_csv("Faculty_salary.csv")
enrollment <- read_csv("grad_enrollment.csv")
phd_field <- read_csv("phd_by_field.csv")
phd_salary <- read_csv("phd_median_salary.csv")


```

```{r}
#part 1
enrollment <- enrollment %>% 
  mutate(male_enroll = males/1000, female_enroll = females/1000)


enrollment_graph <- ggplot(enrollment, aes(x = Year)) +
  geom_line(aes(y = male_enroll)) +
  geom_line(aes(y = female_enroll), color = "blue") +
  theme_classic() +
  scale_x_continuous(expand = c(0,0)) +
  scale_y_continuous(expand = c(0,0)) +
  labs(x = "Year", y = "\n Enrollment  (in thousands) \n")
enrollment_graph

#next step: what kind of stats to perform?


```


```{r, fig.width=11}
#part 2 (figure) Shifts in female PhD recipients by field (1985, 2000, and 2015).

female_recieve <- phd_field %>% 
  filter(year %in% c("1985", "2000", "2015"),
         sex == "female",
         field %in% c("Physical sciences and earth sciences", "Engineering", "Education", "Humanities and arts")) %>% 
  select(1:4)

female_col <- ggplot(female_recieve, aes(field, number, fill = factor(year))) +
  geom_bar(stat="identity", position="dodge") +
  theme_classic() +
  scale_y_continuous(expand = c(0,0), limit = c(0, 5000))
female_col




```


```{r}
#Part 2 (stats) - chi square test: year vs field

female_field <- female_recieve %>% 
  select(-sex) %>% 
  spread(year, number)

female_matrix <- female_field %>% 
  select(-field)

female_prop <- prop.table(as.matrix(female_matrix), 1)

female_chi <- chisq.test(female_matrix)


```





```{r}
#PART 3 (Graph)

postdoc_salary_box <- ggplot(phd_salary, aes(sex, postdoc)) +
  geom_boxplot()+
  theme_classic()+
  xlab("Salary")+
  ylab("Gender")+
  ggtitle("Starting Salaries for Male and Female Postdocs")+
  scale_y_continuous(expand = c(0,0), limit = c(2500,125000))

employ_salary_box <- ggplot(phd_salary, aes(sex, employment)) +
  geom_boxplot()+
  theme_classic()+
  xlab("Salary")+
  ylab("Gender")+
  ggtitle("Starting Salaries for Male and Female pHDs Entering Workforce")+
  scale_y_continuous(expand = c(0,0), limit = c(2500,125000))



```


```{r}
#part 3 (stats) mann-whitney U

#Mann-whitney U - salary btwn m/f starting postdoc positions

#Step 1: perform test
wilcox.test(postdoc ~ sex, data = phd_salary)
#p = 0.867
#Step 2: Cliff's Delta as effect size
postdoc_cd <- cliff.delta(phd_salary$postdoc, phd_salary$sex)
postdoc_cd
#Cliff's delta = -0.04, negligible 

#Mann-whitney U - salary btwn m/f not postdocs

#Step 1: perfrorm test
wilcox.test(employment ~ sex, data = phd_salary)
#p = 0.329
#Step 2: Cliff's Delta as effect size
employment_cd <- cliff.delta(phd_salary$employment, phd_salary$sex)
employment_cd
#Cliff's Delta = -0.213, small



```





```{r, include = FALSE}
#part 4 - build model

salary_lm <- lm(salary ~ sex + discipline + years_phd + years_faculty + rank, data = faculty_salary)
summary(salary_lm)
##R52 = .44


salary_lm2 <- lm(salary ~ sex + discipline + years_faculty + rank, data = faculty_salary)
summary(salary_lm2)
#R^2 = .44
#all significant besides sex - not AS significant as lm3

salary_lm3 <- lm(salary ~ sex + discipline + rank, data = faculty_salary)
summary(salary_lm3)
#R^2 = .44
#all VERY significant but sex

lm1_aic <- AIC(salary_lm)
#9093
lm2_aic <- AIC(salary_lm2)
#9096
lm3_aic <- AIC(salary_lm3)
#9095


```


































